// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKdFF2cvg1Gcspo653PJYJDlTPPkPcTtI',
    appId: '1:17145746919:web:0bb5f84a95c3ae15471942',
    messagingSenderId: '17145746919',
    projectId: 'inicio-sesion-2022-15fd0',
    authDomain: 'inicio-sesion-2022-15fd0.firebaseapp.com',
    databaseURL: 'https://inicio-sesion-2022-15fd0-default-rtdb.firebaseio.com',
    storageBucket: 'inicio-sesion-2022-15fd0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy0quIC_TpqM7JIs_vSd8WqMAZyYP2U3A',
    appId: '1:17145746919:android:51bf18b5d8d76bc9471942',
    messagingSenderId: '17145746919',
    projectId: 'inicio-sesion-2022-15fd0',
    databaseURL: 'https://inicio-sesion-2022-15fd0-default-rtdb.firebaseio.com',
    storageBucket: 'inicio-sesion-2022-15fd0.appspot.com',
  );
}
